// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44366' | (string & {});
};

export type ExternalReferenceModel = {
    documentId: string;
    documentName?: string | null;
    propertyAlias: string;
    targetId: string;
    targetName?: string | null;
};

export type TrueCopyRequestModel = {
    sourceId: string;
    targetParentId?: string | null;
    includeDescendants: boolean;
    relateToOriginal: boolean;
};

export type TrueCopyResultModel = {
    rootCopyId: string;
    rootCopyName?: string | null;
    copiedCount: number;
    documentsChangedCount: number;
    rewrittenLinkCount: number;
    externalReferences: Array<ExternalReferenceModel>;
    externalReferencesTruncated: boolean;
    externalReferenceCount: number;
};

export type PostCopyData = {
    body?: TrueCopyRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/truecopy/api/v1/copy';
};

export type PostCopyErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostCopyResponses = {
    /**
     * OK
     */
    200: TrueCopyResultModel;
};

export type PostCopyResponse = PostCopyResponses[keyof PostCopyResponses];
